#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -exo pipefail

V=""
if [ -n "$VERBOSE" ]; then
  V="-v"
fi
set -u

export DISPLAY=:1

if [ -f "/config/retroarch.cfg" ]; then
  cp /config/retroarch.cfg /root/.config/retroarch/retroarch.cfg
fi

COREPATH=/usr/lib/libretro/"$CORE"_libretro.so
ROMPATH="/roms/$ROM"

retroarch -f $V --libretro "$COREPATH" "$ROMPATH"
