#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -exo pipefail

V=""
if [ -n "$VERBOSE" ]; then
  V="-v"
fi

APPEND_CONFIG=""
if [ -n "$CONFIG" ]; then
  if [ ! -f "$CONFIG" ]; then
    echo "File not found: $CONFIG"
    exit 1
  fi
  APPEND_CONFIG="--appendconfig=$CONFIG"
fi

set -u

export DISPLAY=:1
COREPATH=/usr/lib/libretro/"$CORE"_libretro.so

retroarch -f $V --libretro "$COREPATH" "$ROM" "$APPEND_CONFIG"
